[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
remappings = [
    "@solmate-utils/=lib/solmate/src/utils/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "erc721a/=lib/erc721a/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config